---
services:
  docklens:
    build: .
    container_name: docklens
    ports:
      - "3001:3001"
    volumes:
      # Mount Docker socket to access Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NODE_ENV=production
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
      # Container filtering options:
      # Leave empty or set to "all" to show all containers
      # Set specific container names separated by commas: "app1,app2,database"
      - MONITORED_CONTAINERS=all
      # Container state filtering (all, running, stopped, exited, paused, healthy, etc)
      - CONTAINER_STATES=all
      # Authentication credentials
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=changeme
      # JWT secret for secure websocket
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  monitoring:
    driver: bridge

volumes:
  docker_socket:
    external: true